version: 2

sources:
  - name: staging
    schema: staging
    tables:
      - name: customers
        description: "Raw customer data"
        columns:
          - name: customer_id
            tests:
              - unique
              - not_null
          - name: email
            tests:
              - unique
              - not_null

      - name: orders
        description: "Raw order data"
        columns:
          - name: order_id
            tests:
              - unique
              - not_null
          - name: customer_id
            tests:
              - not_null

      - name: products
        description: "Product catalog"
        
      - name: order_items
        description: "Order line items"
